refactoring arrebol main script we need to be a little more user friendly. I did not test it˜

diff --git a/bin/arrebol b/bin/arrebol
--- a/bin/arrebol
+++ b/bin/arrebol
@@ -1,13 +1,34 @@
 #!/bin/bash
-. Arrebol.properties
+
+. arrebol.properties
+
+print_menu() {
+	echo "Usage: $0 COMMAND [OPTIONS]"
+	echo "Commands are GET, POST, STOP or GETUI"
+	echo "GET | GET [job_id || friendly_name]"
+	echo "POST jdffilepath [s | --schedpath path] [-f | --friendly friendly_name]"
+	echo "STOP [job_id || friendly_name]"
+	exit 1
+}
+
+do_get() {
+	if [ $# -eq 0 ]
+	then
+		response=$(curl -G "$host/sebal-scheduler/job")
+		echo $response
+	elif [ $# -eq 1 ]
+	then
+        	response=$(curl -G "$host/sebal-scheduler/job/$1")
+        	echo $response
+	else
+		print_menu
+		exit 1
+	fi
+}
 
 define_parameters() {
 	while [ ! -z $1 ]; do
 		case $1 in
-			-j | --jdffilepath)
-				shift;
-				jdffilepath=$1;
-				;;
 			-s | --schedpath)
 				shift;
 				schedpath=$1;
@@ -21,78 +42,70 @@ define_parameters() {
 	done
 }
 
-while test $# -gt 0; do
-        case "$1" in
+do_post() {
+	local jdffilepath=$1
+        if [ -f $jdffilepath ]
+	then
+		shift
+        	define_parameters $@
+		base_curl_cmd="curl -X POST --data jdffilepath=${jdffilepath}"
+                if [[ $schedpath ]]
+		then
+			$base_curl_cmd="${base_curl_cmd} --data schedpath=${schedpath}"
+		fi
+                if [[ $friendly ]]
+		then
+			$base_curl_cmd="${base_curl_cmd} --data friendly=${friendly}"
+		fi
+		$base_curl_cmd="${base_curl_cmd} $host/sebal-scheduler/job)"
+	else
+        	echo "Error: jdffilepath<$jdffilepath> not found."
+                exit 1
+        fi
+}
+
+do_stop() {
+	if [ $# -eq 1 ]
+	then
+        	response=$(curl -X DELETE "$host/sebal-scheduler/job/$1")
+                echo $response
+        else
+		print_menu
+		exit 1
+        fi
+}
+
+do_getui() {
+	response=$(curl -G "$host/sebal-scheduler/job/ui")
+	echo $response
+}
+
+if [ $# -gt 0 ]
+then
+	op=$1
+     	case "$op" in
 		GET)
 			shift
-			if test $# -gt 0; then
-				response=$(curl -G "$host/sebal-scheduler/job/$1")
-				echo $response
-			else 
-				response=$(curl -G "$host/sebal-scheduler/job")
-				echo $response
-			fi
-			shift
-			;;
-		POST)
-			shift
-			define_parameters $@
-			if [[ $jdffilepath ]]; then
-				shift
-#FIXME: Encapsular o post num metodo
-				if [[ $friendly ]]; then
-					shift
-					if [[ $schedpath ]]; then
-						response=$(curl -X POST --data jdffilepath=$jdffilepath --data schedpath=$schedpath --data friendly=$friendly $host/sebal-scheduler/job)				
-						echo $response
-						break
-					else
-						response=$(curl -X POST --data jdffilepath=$jdffilepath --data friendly=$friendly $host/sebal-scheduler/job)	
-						echo $response
-						break								
-					fi
-					shift
-				else
-					shift
-					if [[ $schedpath ]]; then
-						response=$(curl -X POST --data jdffilepath=$jdffilepath --data schedpath=$schedpath $host/sebal-scheduler/job)				
-						echo $response
-					else
-						response=$(curl -X POST --data jdffilepath=$jdffilepath $host/sebal-scheduler/job)	
-						echo $response								
-					fi
-					shift
-				fi
-				shift 
-			else 
-				echo "There was no JDF file informed"
-			fi
-			shift
-			;;
-		STOP)
-			shift
-			if test $# -gt 0; then
-				response=$(curl -X DELETE "$host/sebal-scheduler/job/$1")
-				echo $response
-			else 
-				echo "No Id or friendly named was informed"
-			fi
-			shift
-			;;
-
-		GETUI)
-			shift
-				response=$(curl -G "$host/sebal-scheduler/job/ui")
-				echo $response
-			shift
-			;;
-
-		*)
-			echo "no valid function was selected, valid operations are: get, post and stop"
-			break
-			;;
-        esac
-done
-
-
-
+			do_get $@
+                ;;
+            	POST)
+                	shift
+			do_post $@
+                ;;
+            	STOP)
+                	shift
+			do_stop $@
+                ;;
+            	GETUI)
+                	shift
+			do_getui
+                ;;
+            	*)
+			print_menu
+			exit 1
+                ;;
+	esac
+else
+	print_menu
+	exit 1
+fi
